export enum Rol {
  ADMINISTRADOR = 'ADMINISTRADOR',
  COORDINADOR_LOGISTICO = 'COORDINADOR_LOGISTICO',
  OPERADOR_INVENTARIO = 'OPERADOR_INVENTARIO',
  RESPONSABLE_DESTINO = 'RESPONSABLE_DESTINO',
}

export enum EstadoCampania {
  PLANIFICADA = 'PLANIFICADA',
  ACTIVA = 'ACTIVA',
  PAUSADA = 'PAUSADA',
  FINALIZADA = 'FINALIZADA',
  CANCELADA = 'CANCELADA',
}

export enum TipoUbicacion {
  CENTRO_ACOPIO = 'CENTRO_ACOPIO',
  BODEGA = 'BODEGA',
  IGLESIA = 'IGLESIA',
  HOSPITAL = 'HOSPITAL',
  REFUGIO = 'REFUGIO',
  VEHICULO = 'VEHICULO',
  PUNTO_ENTREGA = 'PUNTO_ENTREGA',
  OTRO = 'OTRO',
}

export enum TipoDonante {
  PERSONA = 'PERSONA',
  EMPRESA = 'EMPRESA',
  IGLESIA = 'IGLESIA',
  FUNDACION = 'FUNDACION',
  ANONIMO = 'ANONIMO',
}

export enum EstadoLote {
  DISPONIBLE = 'DISPONIBLE',
  EN_TRANSITO = 'EN_TRANSITO',
  ENTREGADO = 'ENTREGADO',
}

export enum TipoMovimiento {
  ENTRADA = 'ENTRADA',
  TRANSFERENCIA = 'TRANSFERENCIA',
  ENVIO = 'ENVIO',
  RECEPCION = 'RECEPCION',
  AJUSTE = 'AJUSTE',
}

export enum EstadoViaje {
  PLANIFICADO = 'PLANIFICADO',
  EN_TRANSITO = 'EN_TRANSITO',
  RECEPCION_PARCIAL = 'RECEPCION_PARCIAL',
  COMPLETADO = 'COMPLETADO',
  CANCELADO = 'CANCELADO',
}

export enum PrioridadSolicitud {
  BAJA = 'BAJA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
  URGENTE = 'URGENTE',
}

export enum EstadoSolicitud {
  ABIERTA = 'ABIERTA',
  EN_PROCESO = 'EN_PROCESO',
  COMPLETADA = 'COMPLETADA',
  CANCELADA = 'CANCELADA',
}

export enum UnidadMedida {
  UNIDAD = 'UNIDAD',
  KILO = 'KILO',
  LITRO = 'LITRO',
  CAJA = 'CAJA',
  BOLSA = 'BOLSA',
  PAQUETE = 'PAQUETE',
  GALON = 'GALON',
  TONELADA = 'TONELADA',
  PAR = 'PAR',
  OTRO = 'OTRO',
}
